/**
 * Independently reviewed mounted-mode expectations for the registry test.
 * Nothing here is imported by production code or derived from the registry at
 * runtime; changing a mounted mode requires an explicit contract update here.
 */

function deepFreeze(value) {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  for (const nested of Object.values(value)) deepFreeze(nested);
  return Object.freeze(value);
}

const route = (path, roles) => `${path}:${roles}`;
const transport = (kind, channel, serverHandler, clientAdapter, roles, persistence) => (
  `${kind}:${channel}:${serverHandler}:${clientAdapter}:${roles}:${persistence}`
);
const C = (id, routes, transports = []) => ({ id, routeSignatures: routes, transportSignatures: transports });
const SOLO_AI = [
  route('/missions/ai-fight-start', 'start'),
  route('/solo-pve/action', 'action'),
  route('/solo-pve/state', 'state'),
  route('/missions/report-ai-fight', 'settlement'),
];
const PVP_SUPPORT = [
  route('/pvp/chat', 'communication'),
  route('/pvp/spectate', 'lifecycle+observation'),
  route('/pvp/stream', 'observation+state'),
  route('/pvp/combat-log', 'record'),
  route('/pvp/combat-history', 'record'),
  route('/pvp/claim-rewards', 'settlement'),
];
const PVP_RUNTIME = [route('/pvp/session', 'start+state'), route('/pvp/move', 'action'), ...PVP_SUPPORT];
const TOWER_RUNTIME = [
  route('/towers/start', 'start'),
  route('/towers/action', 'action'),
  route('/towers/state', 'state'),
  route('/towers/settle', 'settlement'),
  route('/towers/my-run', 'recovery+state'),
];
const LIVE_PET_DUEL = [transport(
  'socket.io',
  'petduel:*',
  '_realtime/pet-duel-socket',
  'lib/pet-duel-transport.ts',
  'action+settlement+start+state',
  'memory-only',
)];

/** Exact mounted route/role expectations, maintained outside the registry. */
export const EXPECTED_RUNTIME_MODE_CONTRACTS = deepFreeze([
  C('casual-pvp', PVP_RUNTIME),
  C('direct-pvp-challenges', [route('/player/challenge', 'lifecycle'), ...PVP_RUNTIME]),
  C('ranked-shinobi-pvp', [route('/pvp/ranked-queue', 'start'), route('/pvp/ranked-format-weapon', 'start'), route('/ranked-season', 'leaderboard+record'), route('/pvp/session', 'state'), route('/pvp/move', 'action'), ...PVP_SUPPORT]),
  C('village-guard-pvp-human', [route('/village-guard/challenge', 'lifecycle'), ...PVP_RUNTIME]),
  C('kage-succession-pvp', [route('/village/kage-challenge', 'lifecycle+settlement'), ...PVP_RUNTIME]),
  C('clan-war-pvp-1v1', [route('/clan/war/challenge', 'lifecycle'), ...PVP_RUNTIME, route('/clan/war/report', 'settlement')]),
  C('ranked-2v2', [
    route('/pvp/ranked-2v2', 'lifecycle+settlement+start'),
    route('/pvp/ranked-format-weapon', 'start'),
    route('/towers/pvp-action', 'action'),
    route('/towers/pvp-state', 'state'),
  ]),
  C('clan-war-pvp-2v2', [
    route('/clan/war/challenge', 'lifecycle'),
    route('/clan/war/pvp-2v2', 'settlement+start'),
    route('/towers/pvp-action', 'action'),
    route('/towers/pvp-state', 'state'),
  ]),
  C('generic-catalog-ai', SOLO_AI),
  C('temporary-creator-ai', SOLO_AI),
  C('world-context-hunt-trails', [...SOLO_AI, route('/missions/hunt-trail', 'lifecycle')]),
  C('world-context-wanderers', SOLO_AI),
  C('world-context-village-crisis', [...SOLO_AI, route('/world-crisis', 'lifecycle+observation')]),
  C('world-context-hollow-gate-triad', [route('/world-crisis-80', 'lifecycle+observation'), route('/world-crisis-80/combat-start', 'start'), route('/towers/action', 'action'), route('/towers/state', 'state'), route('/world-crisis-80/combat-settle', 'settlement')]),
  C('world-context-hollow-gate-pets', [route('/world-crisis-80', 'lifecycle+observation'), route('/pet/showdown', 'action+settlement+start+state')]),
  C('generic-apex-hunts', SOLO_AI),
  C('generic-explore-ambushes', SOLO_AI),
  C('generic-village-guard-raids', [route('/missions/raid-start', 'lifecycle'), ...SOLO_AI]),
  C('creator-event-practice', SOLO_AI),
  C('combat-missions-ed', [route('/missions/combat-start', 'start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state'), route('/missions/queue-combat-claim', 'settlement'), route('/pve/fight-outcome', 'settlement')]),
  C('combat-missions-cbas', [route('/missions/combat-start', 'start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state'), route('/missions/queue-combat-claim', 'settlement'), route('/pve/fight-outcome', 'settlement')]),
  C('story-battles', [route('/story/boss-start', 'start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state'), route('/story/settle', 'settlement'), route('/pve/fight-outcome', 'settlement')]),
  C('academy-spar', [route('/story/spar-start', 'start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state'), route('/story/settle', 'settlement'), route('/pve/fight-outcome', 'settlement')]),
  C('dungeon-warden', [...SOLO_AI, route('/dungeon/run', 'settlement')]),
  C('weekly-boss', [route('/weekly-boss', 'settlement+start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state')]),
  C('endless', [route('/endless/wave-start', 'start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state'), route('/endless/run', 'settlement')]),
  C('hollow-gate-shinobi', [route('/hollow-gate/combat-start', 'start'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state'), route('/hollow-gate/combat-settle', 'settlement')]),
  C('anbu-infiltration', [route('/village/anbu-infiltration', 'lifecycle+settlement+start+state'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state')]),
  C('battle-towers', [route('/towers/floors', 'catalog'), route('/towers/party', 'lifecycle'), route('/towers/join', 'lifecycle+recovery'), ...TOWER_RUNTIME]),
  C('tower-party', [route('/towers/floors', 'catalog'), route('/towers/party', 'lifecycle'), route('/towers/join', 'lifecycle+recovery'), ...TOWER_RUNTIME]),
  C('endless-spire', [route('/towers/party', 'lifecycle'), route('/towers/join', 'lifecycle+recovery'), ...TOWER_RUNTIME, route('/towers/spire-leaderboard', 'leaderboard')]),
  C('clan-boss', [route('/clan-boss/get', 'leaderboard+state'), route('/clan-boss/party', 'communication+lifecycle'), route('/towers/join', 'lifecycle+recovery'), route('/clan-boss/assault-start', 'start'), route('/towers/action', 'action'), route('/towers/state', 'state'), route('/towers/my-run', 'recovery+state'), route('/clan-boss/assault-settle', 'settlement')]),
  C('tower-pvp', [route('/towers/pvp-queue', 'start'), route('/towers/pvp-action', 'action'), route('/towers/pvp-state', 'state'), route('/towers/pvp-settle', 'settlement')]),
  C('world-sector-player-raid', [
    ...PVP_RUNTIME,
    route('/player/attack', 'lifecycle'),
    route('/player/clear-attack', 'lifecycle'),
    route('/player/challenge', 'lifecycle'),
  ]),
  C('sector-war-shinobi-human', [...PVP_RUNTIME, route('/village/sector-war', 'lifecycle+settlement')]),
  C('sector-war-shinobi-garrison', [route('/village/sector-war', 'lifecycle+settlement+start+state'), route('/solo-pve/action', 'action'), route('/solo-pve/state', 'state')]),
  C('village-war-mercenary', [route('/village/war-merc', 'settlement+start+state'), route('/sector/merc-roam', 'settlement+start+state')]),
  C('sector-war-card', [route('/village/sector-card', 'action+settlement+start+state')]),
  C('sector-war-pet', [route('/village/sector-pet', 'settlement+start+state')]),
  C('clan-war-tilecards', [route('/clan/war/challenge', 'lifecycle'), route('/clan/war/tilecards', 'action+settlement+start+state')]),
  C('clan-war-pet', [route('/clan/war/challenge', 'lifecycle'), route('/clan/war/pet', 'settlement+start+state')]),
  C('pet-showdown-practice', [route('/pet/showdown', 'action+settlement+start+state')]),
  C('wild-pet-binding', [route('/pet/wild-binding', 'action+settlement+start+state')]),
  C('pet-wanderer-showdown', [route('/pet/battle-start', 'recovery+start'), route('/pet/battle-result', 'settlement')]),
  C('pet-coliseum', [route('/pet/showdown', 'action+settlement+start+state')]),
  C('celestial-first-pact', [route('/first-pact/state', 'lifecycle+settlement+state'), route('/pet/showdown', 'action+settlement+start+state')]),
  C('pet-ladder-showdown', [route('/pet-ladder', 'settlement+start+state')]),
  C('pet-warfront', [route('/pet/warfront-start', 'start+state'), route('/pet/battle-result', 'settlement')]),
  C('tactical-arena', []),
  C('coop-tactical-arena', [route('/arena/lobby', 'lifecycle+start+state')]),
  C('pet-ladder-warfront', [route('/pet-ladder', 'settlement+start+state')]),
  C('pet-gauntlet', [route('/pet/gauntlet', 'settlement+start+state')]),
  C('pet-arena-ai-1v1', []),
  C('pet-arena-ai-2v2', []),
  C('pet-arena-ai-issued-token-compat', [route('/pet/battle-start', 'recovery'), route('/pet/battle-result', 'settlement')]),
  C('pet-arena-pvp-1v1', [], LIVE_PET_DUEL),
  C('pet-arena-pvp-2v2', [], LIVE_PET_DUEL),
  C('pet-ranked-live', [
    route('/pvp/pet-ranked-queue', 'lifecycle'),
    route('/pet/ranked-start', 'start'),
    route('/pet/ranked-watch', 'observation+state'),
    route('/pet/battle-result', 'settlement'),
  ]),
  C('pet-ranked-legacy-compat', [route('/player/challenge', 'lifecycle'), route('/pet/ranked-start', 'start+state'), route('/pet/ranked-watch', 'observation+state'), route('/pet/battle-result', 'settlement')]),
  C('hollow-gate-pet-showdown', [route('/hollow-gate/combat-start', 'lifecycle'), route('/pet/showdown', 'action+start+state'), route('/hollow-gate/combat-settle', 'settlement')]),
  C('dungeon-pet-cinematic', [route('/pet/battle-start', 'start+state'), route('/pet/battle-result', 'settlement'), route('/dungeon/run', 'settlement')]),
  C('card-clash-freeplay', [route('/card-clash/queue', 'lifecycle+start'), route('/card-clash/match', 'action+settlement+state')]),
  C('card-clash-ai', [route('/card-clash/ai-start', 'start'), route('/card-clash/ai-move', 'action+settlement+state')]),
  C('echoes-of-war', [route('/card-clash/ai-start', 'start'), route('/card-clash/ai-move', 'action+settlement+state')]),
  C('dungeon-card', [route('/card-clash/ai-start', 'start'), route('/card-clash/ai-move', 'action+settlement+state'), route('/dungeon/run', 'settlement')]),
  C('hollow-gate-rift-card', [route('/hollow-gate/card-start', 'recovery+start'), route('/card-clash/ai-move', 'action+settlement+state'), route('/hollow-gate/card-settle', 'settlement')]),
]);

const F = (authorityEngine, intendedAuthorityEngine, participantModel, rewardPolicy, status) => ({
  authorityEngine,
  intendedAuthorityEngine,
  participantModel,
  rewardPolicy,
  status,
});

/** Independent semantic facts for every product mode, not just high-risk rows. */
export const EXPECTED_RUNTIME_MODE_FACTS = deepFreeze({
  'casual-pvp': F('pvp', null, 'two-player', 'none', 'match'),
  'direct-pvp-challenges': F('pvp', null, 'two-player', 'none', 'match'),
  'ranked-shinobi-pvp': F('pvp', null, 'two-player', 'server-settled', 'match'),
  'village-guard-pvp-human': F('pvp', null, 'two-player', 'server-settled', 'match'),
  'kage-succession-pvp': F('pvp', null, 'two-player', 'server-settled', 'match'),
  'clan-war-pvp-1v1': F('pvp', null, 'two-player', 'server-settled', 'match'),
  'ranked-2v2': F('tower', 'pvp', 'party', 'server-settled', 'match'),
  'clan-war-pvp-2v2': F('tower', 'pvp', 'party', 'server-settled', 'match'),
  'generic-catalog-ai': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'temporary-creator-ai': F('solo-pve', null, 'solo', 'none', 'match'),
  'world-context-hunt-trails': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'world-context-wanderers': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'world-context-village-crisis': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'world-context-hollow-gate-triad': F('tower', null, 'solo', 'parent-mode-settlement', 'match'),
  'world-context-hollow-gate-pets': F('pet-showdown', null, 'party', 'parent-mode-settlement', 'match'),
  'generic-apex-hunts': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'generic-explore-ambushes': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'generic-village-guard-raids': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'creator-event-practice': F('solo-pve', null, 'solo', 'none', 'match'),
  'combat-missions-ed': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'combat-missions-cbas': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'story-battles': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'academy-spar': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'dungeon-warden': F('solo-pve', null, 'solo', 'parent-mode-settlement', 'match'),
  'weekly-boss': F('solo-pve', null, 'solo', 'server-capped', 'match'),
  endless: F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'hollow-gate-shinobi': F('solo-pve', null, 'solo', 'parent-mode-settlement', 'match'),
  'anbu-infiltration': F('solo-pve', null, 'solo', 'server-settled', 'match'),
  'battle-towers': F('tower', null, 'solo-or-party', 'server-settled', 'match'),
  'tower-party': F('tower', null, 'party', 'server-settled', 'match'),
  'endless-spire': F('tower', null, 'party', 'server-capped', 'match'),
  'clan-boss': F('tower', null, 'solo-or-party', 'server-settled', 'match'),
  'tower-pvp': F('tower', null, 'party', 'none', 'match'),
  'world-sector-player-raid': F('pvp', null, 'two-player', 'server-settled', 'match'),
  'sector-war-shinobi-human': F('pvp', null, 'two-player', 'server-settled', 'match'),
  'sector-war-shinobi-garrison': F('pvp', null, 'solo', 'server-settled', 'match'),
  'village-war-mercenary': F('tower', null, 'headless', 'server-settled', 'match'),
  'sector-war-card': F('chronicle', null, 'two-player', 'server-settled', 'match'),
  'sector-war-pet': F('pet-showdown', null, 'two-player', 'server-settled', 'match'),
  'clan-war-tilecards': F('chronicle', null, 'two-player', 'server-settled', 'match'),
  'clan-war-pet': F('pet-showdown', null, 'party', 'server-settled', 'match'),
  'pet-showdown-practice': F('pet-showdown', null, 'solo', 'none', 'match'),
  'wild-pet-binding': F('pet-showdown', null, 'solo', 'server-settled', 'match'),
  'pet-wanderer-showdown': F('pet-showdown', null, 'solo', 'none', 'match'),
  'pet-coliseum': F('pet-showdown', null, 'solo', 'server-capped', 'match'),
  'celestial-first-pact': F('pet-showdown', null, 'solo', 'server-progression', 'match'),
  'pet-ladder-showdown': F('pet-showdown', null, 'asynchronous-defense', 'server-settled', 'match'),
  'pet-warfront': F('pet-warfront', null, 'solo', 'server-capped', 'match'),
  'tactical-arena': F(null, 'pet-warfront', 'solo', 'none', 'surface-gap'),
  'coop-tactical-arena': F('pet-warfront', null, 'party', 'none', 'match'),
  'pet-ladder-warfront': F('pet-warfront', null, 'asynchronous-defense', 'server-settled', 'match'),
  'pet-gauntlet': F('pet-gauntlet-grid', null, 'solo', 'server-capped', 'match'),
  'pet-arena-ai-1v1': F(null, 'pet-cinematic-duel', 'solo', 'none', 'surface-gap'),
  'pet-arena-ai-2v2': F(null, 'pet-cinematic-duel', 'solo', 'none', 'surface-gap'),
  'pet-arena-ai-issued-token-compat': F('pet-cinematic-duel', null, 'solo', 'server-capped', 'match'),
  'pet-arena-pvp-1v1': F('pet-cinematic-duel', null, 'two-player', 'none', 'match'),
  'pet-arena-pvp-2v2': F('pet-cinematic-duel', null, 'two-player', 'none', 'match'),
  'pet-ranked-live': F('pet-showdown', null, 'two-player', 'server-settled', 'match'),
  'pet-ranked-legacy-compat': F('pet-showdown', null, 'two-player', 'server-settled', 'match'),
  'hollow-gate-pet-showdown': F('pet-showdown', null, 'solo', 'parent-mode-settlement', 'match'),
  'dungeon-pet-cinematic': F('pet-cinematic-duel', null, 'solo', 'parent-mode-settlement', 'match'),
  'card-clash-freeplay': F('chronicle', null, 'two-player', 'server-progression', 'match'),
  'card-clash-ai': F('chronicle', null, 'solo', 'server-capped', 'match'),
  'echoes-of-war': F('chronicle', null, 'solo', 'server-settled', 'match'),
  'dungeon-card': F('chronicle', null, 'solo', 'parent-mode-settlement', 'match'),
  'hollow-gate-rift-card': F('chronicle', null, 'solo', 'parent-mode-settlement', 'match'),
});

/** Capability bindings are independently pinned because a valid capability id
 * can still be the wrong operational boundary (for example ANBU vs Sector Map). */
export const EXPECTED_RUNTIME_CAPABILITY_BINDINGS = deepFreeze({
  'anbu-infiltration': 'anbuInfiltration',
  'clan-boss': 'clanBoss',
  'sector-war-shinobi-human': 'villageWar',
  'sector-war-shinobi-garrison': 'villageWar',
  'village-war-mercenary': 'villageWar',
  'sector-war-card': 'villageWar',
  'sector-war-pet': 'villageWar',
});

const M = (category, replayKind, orchestrationOwner = null) => ({ category, replayKind, orchestrationOwner });

/** Independent category, replay/history, and parent-orchestration facts. */
export const EXPECTED_RUNTIME_MODE_METADATA = deepFreeze({
  'casual-pvp': M('shinobi-pvp', 'durable-pvp-history'),
  'direct-pvp-challenges': M('shinobi-pvp', 'durable-pvp-history'),
  'ranked-shinobi-pvp': M('shinobi-pvp', 'durable-pvp-history'),
  'village-guard-pvp-human': M('shinobi-pvp', 'durable-pvp-history-plus-expiring-defense-marker'),
  'kage-succession-pvp': M('shinobi-pvp', 'durable-pvp-history-plus-succession-record'),
  'clan-war-pvp-1v1': M('shinobi-pvp', 'durable-pvp-history', 'clan-war'),
  'ranked-2v2': M('shinobi-pvp', 'bounded-terminal-command-ring'),
  'clan-war-pvp-2v2': M('shinobi-pvp', 'bounded-terminal-command-ring', 'clan-war'),
  'generic-catalog-ai': M('solo-pve', 'expiring-solo-session-log'),
  'temporary-creator-ai': M('solo-pve', 'expiring-solo-session-log'),
  'world-context-hunt-trails': M('solo-pve', 'expiring-solo-session-log'),
  'world-context-wanderers': M('solo-pve', 'expiring-solo-session-log'),
  'world-context-village-crisis': M('solo-pve', 'expiring-solo-session-log-plus-global-crisis-ledger'),
  'world-context-hollow-gate-triad': M('tower', 'expiring-tower-run-plus-global-crisis-proof'),
  'world-context-hollow-gate-pets': M('pet-showdown', 'expiring-showdown-turn-script-plus-global-crisis-proof'),
  'generic-apex-hunts': M('solo-pve', 'expiring-solo-session-log'),
  'generic-explore-ambushes': M('solo-pve', 'expiring-solo-session-log'),
  'generic-village-guard-raids': M('solo-pve', 'expiring-solo-session-log'),
  'creator-event-practice': M('solo-pve', 'expiring-solo-session-log'),
  'combat-missions-ed': M('solo-pve', 'expiring-solo-session-log'),
  'combat-missions-cbas': M('solo-pve', 'expiring-solo-session-log'),
  'story-battles': M('solo-pve', 'expiring-solo-session-log'),
  'academy-spar': M('solo-pve', 'expiring-solo-session-log'),
  'dungeon-warden': M('solo-pve', 'expiring-solo-session-log', 'dungeon'),
  'weekly-boss': M('solo-pve', 'expiring-solo-session-log'),
  endless: M('solo-pve', 'expiring-run-and-session'),
  'hollow-gate-shinobi': M('solo-pve', 'expiring-run-and-session', 'hollow-gate'),
  'anbu-infiltration': M('solo-pve', 'expiring-run-and-session-with-receipt'),
  'battle-towers': M('tower', 'expiring-tower-run-and-log'),
  'tower-party': M('tower', 'expiring-tower-run-and-log'),
  'endless-spire': M('tower', 'expiring-tower-run-and-log'),
  'clan-boss': M('tower', 'expiring-tower-session-and-aggregate-standings'),
  'tower-pvp': M('tower', 'bounded-terminal-command-ring'),
  'world-sector-player-raid': M('shinobi-pvp', 'durable-pvp-history'),
  'sector-war-shinobi-human': M('shinobi-pvp', 'durable-pvp-history-plus-contest-receipt', 'sector-war'),
  'sector-war-shinobi-garrison': M('shinobi-pvp', 'expiring-solo-session-log-plus-contest-receipt', 'sector-war'),
  'village-war-mercenary': M('tower', 'contest-receipt-only', 'sector-war'),
  'sector-war-card': M('card', 'expiring-chronicle-projection', 'sector-war'),
  'sector-war-pet': M('pet-showdown', 'derived-showdown-script', 'sector-war'),
  'clan-war-tilecards': M('card', 'expiring-chronicle-projection', 'clan-war'),
  'clan-war-pet': M('pet-showdown', 'derived-showdown-script', 'clan-war'),
  'pet-showdown-practice': M('pet-showdown', 'expiring-showdown-turn-script'),
  'wild-pet-binding': M('pet-showdown', 'expiring-showdown-turn-script'),
  'pet-wanderer-showdown': M('pet-showdown', 'immutable-returned-showdown-script'),
  'pet-coliseum': M('pet-showdown', 'expiring-showdown-turn-script'),
  'celestial-first-pact': M('pet-showdown', 'durable-campaign-plus-expiring-showdown-turn-script'),
  'pet-ladder-showdown': M('pet-showdown', 'returned-showdown-script'),
  'pet-warfront': M('pet-tactical', 'sealed-warfront-presentation-replay'),
  'tactical-arena': M('pet-legacy', 'none'),
  'coop-tactical-arena': M('pet-tactical', 'client-warfront-replay-from-server-sealed-inputs'),
  'pet-ladder-warfront': M('pet-tactical', 'sealed-rite-formations-and-seed'),
  'pet-gauntlet': M('pet-tactical', 'server-replayed-decision-transcript-and-receipt'),
  'pet-arena-ai-1v1': M('pet-legacy', 'none'),
  'pet-arena-ai-2v2': M('pet-legacy', 'none'),
  'pet-arena-ai-issued-token-compat': M('pet-legacy', 'server-replayed-cinematic-input-log-with-receipt'),
  'pet-arena-pvp-1v1': M('pet-legacy', 'memory-only-server-replayed-lockstep-cinematic-log'),
  'pet-arena-pvp-2v2': M('pet-legacy', 'memory-only-server-replayed-lockstep-cinematic-log'),
  'pet-ranked-live': M('pet-showdown', 'derived-showdown-script'),
  'pet-ranked-legacy-compat': M('pet-legacy', 'derived-showdown-script'),
  'hollow-gate-pet-showdown': M('pet-showdown', 'expiring-showdown-turn-script-plus-parent-run-receipt', 'hollow-gate'),
  'dungeon-pet-cinematic': M('pet-legacy', 'server-replayed-cinematic-input-log-and-parent-run-receipt', 'dungeon'),
  'card-clash-freeplay': M('card', 'expiring-chronicle-projection'),
  'card-clash-ai': M('card', 'expiring-chronicle-projection'),
  'echoes-of-war': M('card', 'expiring-chronicle-projection'),
  'dungeon-card': M('card', 'expiring-chronicle-projection-and-parent-run-proof-receipt', 'dungeon'),
  'hollow-gate-rift-card': M('card', 'expiring-chronicle-projection-and-parent-run-proof-receipt', 'hollow-gate'),
});

/**
 * Independent reverse-census boundary for mounted Express routes and client
 * route literals. A matching route must be assigned to a mode above or carry
 * one explicit, reviewable reason for remaining outside combat authority.
 */
export const COMBAT_ROUTE_CENSUS = deepFreeze({
  prefixes: [
    '/pvp/',
    '/towers/',
    '/clan-boss/',
    '/card-clash/',
    '/pet/',
    '/village-guard/',
    '/clan/war/',
    '/hollow-gate/',
    '/missions/',
    '/solo-pve/',
    '/story/',
    '/endless/',
    '/world-crisis-80/',
  ],
  exactPaths: [
    '/player/challenge',
    '/player/sleeper-kill',
    '/arena/lobby',
    '/pet-ladder',
    '/weekly-boss',
    '/dungeon/run',
    '/village/anbu-infiltration',
    '/village/kage-challenge',
    '/village/war-merc',
    '/village/sector-war',
    '/village/sector-card',
    '/village/sector-pet',
    '/pve/fight-outcome',
    '/battle/lock',
    '/ranked-season',
    '/sector/merc-roam',
    '/world-crisis-80',
  ],
  exclusions: {
    '/battle/lock': 'Cross-mode admission mutex; it does not resolve or settle a combat runtime.',
    '/player/sleeper-kill': 'Server-settled free knockout with no combat session or action loop. Deliberately excluded rather than modelled: it pays real PvP rewards (base ryo, a kill credit, capped Vanguard seals) but owns no session, no turn loop and no second participant, so it has nothing for this census to assert. Re-checked by the 2026-08-30 sector-PvP audit and kept excluded.',
    '/pvp/bounty': 'PvP bounty-board metagame CRUD; it does not own a battle session.',
    '/village-guard/queue': 'Guard-duty enrollment, outside the combat session runtime.',
    '/village-guard/dequeue': 'Guard-duty enrollment, outside the combat session runtime.',
    '/village-guard/list': 'Guard roster projection, outside the combat session runtime.',
    '/clan/war/list': 'Clan-war status projection; combat ownership starts at the registered challenge routes.',
    '/clan/war/declare': 'Clan-war campaign administration; it does not resolve a combat session.',
    '/card-clash/open-pack': 'Card inventory acquisition, outside Chronicle match authority.',
    '/card-clash/claim-starter': 'One-time card inventory grant, outside Chronicle match authority.',
    '/card-clash/sync-progression': 'Progression synchronization, outside Chronicle match authority.',
    '/card-clash/echoes-witness': 'Server-owned narrative record after an authoritative Echoes clear; it neither starts nor settles a Chronicle match and grants no reward.',
    '/pet/evolve': 'Pet progression mutation, outside pet combat authority.',
    '/pet/befriend': 'Pet acquisition settlement, outside pet combat authority.',
    '/pet/encounter-decline': 'Pet acquisition lifecycle, outside pet combat authority.',
    '/pet/choose-starter': 'Pet roster initialization, outside pet combat authority.',
    '/pet/encounter-start': 'Pet acquisition encounter minting, outside pet combat authority.',
    '/pet/progress': 'Pet training/progression mutation, outside pet combat authority.',
    '/pet/breeding/status': 'Breeding status projection, outside pet combat authority.',
    '/pet/breeding/start': 'Breeding lifecycle, outside pet combat authority.',
    '/pet/breeding/hatch': 'Breeding settlement, outside pet combat authority.',
    '/pet/sanctuary/list': 'Pet storage projection, outside pet combat authority.',
    '/pet/sanctuary/transfer': 'Pet storage transfer, outside pet combat authority.',
    '/hollow-gate/start': 'Parent expedition lifecycle; per-fight authority begins at combat-start.',
    '/hollow-gate/descend': 'Parent expedition navigation, outside the embedded combat runtime.',
    '/hollow-gate/choose-augment': 'Parent expedition build choice, outside the embedded combat runtime.',
    '/hollow-gate/settle': 'Parent expedition finalization, outside an individual embedded fight.',
    '/hollow-gate/use-consumable': 'Parent expedition inventory action, outside the embedded combat runtime.',
    '/hollow-gate/event': 'Parent expedition event resolution, outside the embedded combat runtime.',
    '/hollow-gate/step': 'Parent expedition navigation, outside the embedded combat runtime.',
    '/hollow-gate/floor-seal': 'Parent expedition floor checkpoint, outside the embedded combat runtime.',
    '/hollow-gate/resume': 'Parent expedition reload projection, outside the embedded combat runtime; an open fight still resumes through combat-start.',
    '/hollow-gate/attune': 'Parent expedition unlock/progression, outside the embedded combat runtime.',
    '/hollow-gate/forge-key': 'Parent expedition inventory crafting, outside the embedded combat runtime.',
    '/hollow-gate/locked-door': 'Parent expedition door event, outside the embedded combat runtime.',
    '/missions/daily': 'Mission-board projection, outside combat authority.',
    '/missions/weekly-board': 'Mission-board progression, outside combat authority.',
    '/missions/report-raid': 'Mission progression receipt; authoritative raid combat settles through report-ai-fight.',
    '/missions/report-pvp-win': 'Mission progression receipt; it does not own or settle the PvP session.',
    '/missions/report-pet-event': 'Pet expedition progression receipt, outside pet combat authority.',
    '/missions/expedition-start': 'Pet expedition lifecycle, outside pet combat authority.',
    '/missions/field-trail': 'Non-combat mission progression lifecycle.',
    '/missions/claim-mission': 'Mission reward claim, outside the embedded combat runtime.',
    '/missions/record-progress': 'Generic mission progression receipt, outside combat authority.',
    '/story/interlude': 'Narrative progression, outside Solo-PvE combat authority.',
    '/story/road-event': 'Narrative road-event progression, outside Solo-PvE combat authority.',
  },
});
